orderbook_manager:
  market_allocations:
    # configs are always "market_base" format
    DOGE_BTC:
      BTC: .6
      DOGE: 1
    LTC_BTC:
      BTC: .2
      LTC: 1
    NANO_BTC:
      BTC: .2
      NANO: 1
  currency_reserves:
    DOGE: 0.01
    BTC: 0.00000010
    LTC: 0.001
    NANO: 0.0000010

  intervals:
    buy_limit:
      0.03: 0.1
      0.05: 0.15
      0.09: 0.2
      0.13: 0.25
      0.20: 0.3
    sell_limit:
      0.03: 0.1
      0.05: 0.15
      0.09: 0.2
      0.13: 0.25
      0.20: 0.3
  monitor_period: 300
  reserve_thresh_usd: 1.00
  price_tolerance: .01
  amount_tolerance: .05
  dry_run_mode: False
  cost_basis_btc: 0.164724101

market_data_collector:
  update_period: 300
  scrapers:
    qtrade:
      markets: {'DOGE_BTC':'DOGE_BTC', 'LTC_BTC':'LTC_BTC'}
    bittrex:
      markets: {'BTC-DOGE':'DOGE_BTC', 'BTC-LTC':'LTC_BTC'}
    ccxt:
      markets: {'NANO/BTC':'NANO_BTC'}
      exchanges: ['binance', 'kucoin', 'kraken']
