orderbook_manager:
  markets:
    # configs are always "market_base" format
    DOGE_BTC:
      BTC: .25
      DOGE: .8
    LTC_BTC:
      BTC: .15
      LTC: .8
      intervals:
        buy_limit:
          0.03: 0.1
          0.05: 0.125
          0.09: 0.15
          0.13: 0.275
          0.20: 0.35
        sell_limit:
          0.03: 0.1
          0.05: 0.125
          0.09: 0.15
          0.13: 0.275
          0.20: 0.35
    NANO_BTC:
      BTC: .15
      NANO: .8
    ETH_BTC:
      BTC: .25
      ETH: .8
    default:
      intervals:
        buy_limit:
          0.03: 0.1
          0.05: 0.15
          0.09: 0.2
          0.13: 0.25
          0.20: 0.3
        sell_limit:
          0.03: 0.1
          0.05: 0.15
          0.09: 0.2
          0.13: 0.25
          0.20: 0.3

  currency_reserves:
    DOGE: 0.01
    BTC: 0.00000010
    LTC: 0.001
    NANO: 0.0000010
    ETH: 0.0000010

  monitor_period: 300
  reserve_thresh_usd: 1.00
  price_tolerance: .01
  amount_tolerance: .05
  dry_run_mode: True
  cost_basis_btc: 0.164724101

market_data_collector:
  update_period: 300
  scrapers:
    qtrade:
      markets: {'DOGE_BTC':'DOGE_BTC', 'LTC_BTC':'LTC_BTC', 'ARO_BTC':'ARO_BTC'}
    bittrex:
      markets: {'BTC-DOGE':'DOGE_BTC', 'BTC-LTC':'LTC_BTC', 'BTC-ETH':'ETH_BTC'}
    ccxt:
      markets: {'NANO/BTC':'NANO_BTC'}
      exchanges: ['binance', 'kucoin', 'kraken']

vol_bot_manager:
  markets:
    DOGE_BTC:
      BTC: .05
      DOGE: .2
    LTC_BTC:
      BTC: .05
      LTC: .2
    NANO_BTC:
      BTC: .05
      NANO: .2
    ETH_BTC:
      BTC: .05
      ETH: .2
  currency_reserves:
    DOGE: 0.01
    BTC: 0.00000010
    LTC: 0.001
    NANO: 0.0000010
    ETH: 0.0000010
  dry: True
  default:
    q: 100
    var: 2
    amount: .3
  

