orderbook_manager:
  market_allocations:
    # configs are always "market_base" format
    DOGE_BTC:
      BTC: .7
      DOGE: 1
    LTC_BTC:
      BTC: .3
      LTC: 1
  currency_reserves:
    DOGE: 0
    BTC: 0
    LTC: 0

  intervals:
    buy_limit:
      0.03: 0.2
      0.05: 0.3
      0.09: 0.3
      0.13: 0.1
      0.20: 0.1
    sell_limit:
      0.03: 0.2
      0.05: 0.3
      0.09: 0.3
      0.13: 0.1
      0.20: 0.1
  monitor_period: 300
  reserve_tolerance: .05
  price_tolerance: .01
  amount_tolerance: .05
  dry_run_mode: False

market_data_collector:
  update_period: 300
  scrapers:
    qtrade:
      markets: {'DOGE_BTC':'DOGE_BTC', 'LTC_BTC':'LTC_BTC'}
    bittrex:
      markets: {'BTC-DOGE':'DOGE_BTC', 'BTC-LTC':'LTC_BTC'}
