orderbook_manager:
  market_allocations:
    # configs are always "market_base" format
    DOGE_BTC:
      BTC: 1
      DOGE: 1
  currency_reserves:
    DOGE: 100
    BTC: 0.00001

  intervals:
    buy:
      0.02: 0.2
      0.04: 0.5
      0.05: 0.3
    sell:
      0.02: 0.2
      0.04: 0.5
      0.05: 0.3
  monitor_period: 3
  reserve_margin: .05

market_data_collector:
  update_period: 3
  scrapers:
    qtrade:
      markets: ['DOGE_BTC']
