orderbook_manager:
  market_allocations:
    # configs are always "market_base" format
    DOGE_BTC:
      BTC: 1
      DOGE: 1
  currency_reserves:
    DOGE: 100
    BTC: 0.00001

  intervals: # can't place all orders if ratios add to 1?
    buy:
      0.03: 0.2
      0.05: 0.3
      0.09: 0.3
      0.13: 0.1
      0.20: 0.1
    sell:
      0.03: 0.2
      0.05: 0.3
      0.09: 0.3
      0.13: 0.1
      0.20: 0.1
  monitor_period: 60
  reserve_tolerance: .05
  price_tolerance: .01
  amount_tolerance: .05
  dry_run_mode: True
  prevent_taker: True

market_data_collector:
  update_period: 60
  scrapers:
    qtrade:
      markets: {'DOGE_BTC':'DOGE_BTC'}
    bittrex:
      markets: {'BTC-DOGE':'DOGE_BTC'}
