orderbook_manager:
  allocations:
    BTC:
      DOGE: 0.01
      reserve: 0.01
      target: 0.03
    DOGE:
      BTC: 1000
      reserve: 1000
      target: 25000
  intervals:
    buy:
      0.02: 0.2
      0.04: 0.5
      0.05: 0.3
    sell:
      0.02: 0.2
      0.04: 0.5
      0.05: 0.3
  monitor_period: 3
  reserve_margin: .05

market_data_collector:
  update_period: 3
  scrapers:
    qtrade:
      markets: ['DOGE_BTC']
